---
     environment: production
     chdir: "/opt/metahacker.me"
     address: 127.0.0.1
     # user: web
     # group: web
     port: 4567
     pid: "/tmp/thin.pid"
     rackup: "/opt/metahacker.me/configs/config.ru"
     log: "/var/log/thin/metahacker.log"
     max_conns: 1024
     timeout: 30
     servers: 1
     max_persistent_conns: 512
     daemonize: true
